version: "3"

services:
  app:
    build: .
    working_dir: /go/src
    ports:
      - "8888:8888"
    volumes:
      - .:/go/src
    command: go run currency.go
    links:
      - redis
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: my-bridge-network
